name: DisplayShops
main: xzot1k.plugins.ds.DisplayShops
version: ${project.version}-${core.build}
api-version: 1.13
author: XZot1K
description: Create immersive simplistic shops with animations, efficient transaction handling, and much more!
softdepend: [ Vault, HeadDatabase, Prisma, PlaceholderAPI, PlotSquared, BentoBox, BSkyBlock, Oneblock, CMI, MultiWorld, Multiverse-Core,
              ASkyBlock, USkyBlock, FabledSkyBlock, PlayerWorldsPro, WorldGuard, WorldEdit, ItemsAdder ]
loadbefore: [ GriefPrevention, JetsMinions ]
loadafter: [ ]
load: POSTWORLD

commands:
  displayshops:
    default: op
    description: The main command for the DisplayShops plugin.
    aliases: [ ds ]

permissions:
  displayshops.*:
    default: op
    description: Gives all permissions contained in the plugin.
    children:
      displayshops.user: true
      displayshops.give: true
      displayshops.admin: true
      displayshops.reload: true
      displayshops.stock: true
      displayshops.owner: true
      displayshops.cmr: true
      displayshops.dmr: true
      displayshops.sm: true
      displayshops.mrl: true
      displayshops.adminhelp: true
      displayshops.admindelete: true
      displayshops.cdbypass: true
      displayshops.info: true
      displayshops.cleanup: true
      displayshops.bbmaccess: true
      displayshops.clear: true
      displayshops.reset: true
      displayshops.block: true
      displayshops.cost: true
      displayshops.rcost: true

  displayshops.user:
    default: op
    description: Gives all permissions that were made for a normal player.
    children:
      displayshops.buy: true
      displayshops.create: true
      displayshops.delete: true
      displayshops.craft: true
      displayshops.visit: true
      displayshops.copy: true
      displayshops.help: true
      displayshops.rent: true
      displayshops.edit: true
      displayshops.assistants: true
      displayshops.description: true
      displayshops.advertise: true
      displayshops.notify: true
      displayshops.buyprice: true
      displayshops.sellprice: true
      displayshops.withdraw: true
      displayshops.deposit: true
      displayshops.balwithdraw: true
      displayshops.baldeposit: true

  displayshops.buy:
    default: op
    description: Allows the player to buy one shop creation item from the server.
  displayshops.give:
    default: op
    description: Allows the sender to give display shop creation items to players.
  displayshops.admin:
    default: op
    description: Allows the player to set the shop in their line of sight to admin mode and bypass the visit command charge.
  displayshops.reload:
    default: op
    description: Allows the sender to reload the shops, configurations, etc.
  displayshops.create:
    default: op
    description: Allows the player to create new shops.
  displayshops.help:
    default: op
    description: Allows the sender to view the user help message.
  displayshops.edit:
    default: op
    description: Allows the player to do anything to any shop without being the rightful owner.
  displayshops.bypass:
    default: op
    description: Allows the player to bypass the charge when buying from a shop (Owner still gets the amount).
  displayshops.stock:
    default: op
    description: Allows the player to set the stock of the shop they are looking at.
  displayshops.owner:
    default: op
    description: Allows the player to set the owner of the shop they are looking at.
  displayshops.cmr:
    default: op
    description: Allows the player to create a market region.
  displayshops.dmr:
    default: op
    description: Allows the player to delete a market region.
  displayshops.sm:
    default: op
    description: Allows the player to enter region selection mode.
  displayshops.mrl:
    default: op
    description: Allows the player to view all market region ids.
  displayshops.commands:
    default: op
    description: Allows the player to manage commands of admin shops.
  displayshops.delete:
    default: op
    description: Allows the player to delete owned shops.
  displayshops.adminhelp:
    default: op
    description: The admin help message will be shown instead of the user help message.
  displayshops.admindelete:
    default: op
    description: Allows the player to delete a shop even if they do not own it or it is an admin shop.
  displayshops.cdbypass:
    default: op
    description: Allows the player to bypass any cooldowns the plugin uses.
  displayshops.craft:
    default: op
    description: Allows the player to craft the shop creation item.
  displayshops.info:
    default: op
    description: Allows the player to see information about the current plugin build.
  displayshops.visit:
    default: op
    description: Allows the player to teleport to a safe location near a shop.
  displayshops.copy:
    default: op
    description: Allows the player to obtain an ID from a shop currently in view through command.
  displayshops.cleanup:
    default: op
    description: Allows the player to use the shop cleanup command.
  displayshops.assistants:
    default: op
    description: Allows the player to add/remove assistants from a shop as long as access to the edit menu is provided.
  displayshops.description:
    default: op
    description: Allows the player to modify a shop's description.
  displayshops.bbmaccess:
    default: op
    description: Allows the player to unlock/lock all base-block materials for a player using the unlock/lock commands.
  displayshops.clear:
    default: op
    description: Allows the sender to use the clear command to remove all shops from a defined world.
  displayshops.rent:
    default: op
    description: Allows the player to use the rent command to rent out a market region.
  displayshops.reset:
    default: op
    description: Allows the sender to completely reset a market region releasing any for of rent data.
  displayshops.block:
    default: op
    description: This allows the player to block the item in-hand from being sold in shops.
  displayshops.advertise:
    default: op
    description: Allows the player to advertise their shop via command.
  displayshops.notify:
    default: op
    description: Allows the player to toggle shop sale notifications for themselves.
  displayshops.buyprice:
    default: op
    description: Allows the player to set the buy price of a shop they can access via command.
  displayshops.sellprice:
    default: op
    description: Allows the player to set the sell price of a shop they can access via command.
  displayshops.cost:
    default: op
    description: Allows the player to use the market region rent cost command.
  displayshops.rcost:
    default: op
    description: Allows the player to use the market region rent renewal cost command.
  displayshops.withdraw:
    default: op
    description: Allows the player to use the withdraw stock command.
  displayshops.deposit:
    default: op
    description: Allows the player to use the deposit stock command.
  displayshops.balwithdraw:
    default: op
    description: Allows the player to use the withdraw balance command.
  displayshops.baldeposit:
    default: op
    description: Allows the player to use the deposit balance command.